#!/bin/sh 

[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/zdcleint ) && rm -f /etc/uci-defaults/zdcleint
	chmod 755 /etc/init.d/zdcleint >/dev/null 2>&1
   /etc/init.d/zdcleint enable >/dev/null 2>&1

	exit 0
}
